name: Post content automatically to Mastodon

on:
  schedule:
    # Runs at 9AM every weekday
    # https://crontab.guru/#0_9_*_*_1-5
    - cron:  '0 9 * * 1-5'
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    env: 
      TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
      URL: ${{ secrets.MASTODON_URL }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pandas
        pip install Mastodon.py
    - name: Run script
      id: script_output
      run: python scripts/social-media-bot/bot-content.py
