name: Post content automatically to Mastodon

on:
  schedule:
    # Runs at 9AM every weekday
    # https://crontab.guru/#0_9_*_*_1-5
    - cron:  '0 9 * * 1-5'
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run Python script
      id: run-script
      run: |
        echo "OUTPUT=$(python3 scripts/social-media-bot/bot-content.py)" >> $GITHUB_OUTPUT
    - name: Send toot to Mastodon
      id: mastodon
      uses: cbrgm/mastodon-github-action@v2
      with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }} # access token
          url: ${{ secrets.MASTODON_URL }} # https://example.social
          message: ${{ steps.sets-value.outputs.OUTPUT }}
